Repository ucsb-cs156-f24/proj-happycows-f24-10, pull requests merged in 2024-11, with the labels that each got.

#14 Use title case for Buy/Sell button in modal
  frontend/src/main/components/Commons/ManageCowsModal.js
  frontend/src/tests/components/Commons/ManageCowsModal.test.js
Labels: 5

#15 Corrected link to Professor de Vries' About Page
  frontend/src/main/components/Nav/Footer.js
Labels: 5, Merge Candidate-CI

#17 Fix explanation for buying and selling cows to be more readable
  frontend/src/main/components/Commons/ManageCows.js
Labels: 5, Merge Candidate-CI

#19 Fix bug with wealth sorting mishandling commas
  frontend/src/fixtures/leaderboardFixtures.js
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
Labels: 10

#32 Add Entity, Repository and Migration for Course table
  src/main/java/edu/ucsb/cs156/happiercows/entities/Course.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CourseRepository.java
  src/main/resources/db/migration/changes/Courses.json
Labels: enhancement, 5, Merge Candidate-CI

#33 Add Student.java entity file and Student.json migration file
  src/main/java/edu/ucsb/cs156/happiercows/entities/Student.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/StudentRepository.java
  src/main/resources/db/migration/changes/Student.json
Labels: 5, Merge Candidate-CI

#49 Create placeholder pages for Student table
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminStudentsCreatePage.js
  frontend/src/main/pages/AdminStudentsEditPage.js
  frontend/src/main/pages/AdminStudentsIndexPage.js
  frontend/src/tests/pages/AdminStudentsCreatePage.test.js
  frontend/src/tests/pages/AdminStudentsEditPage.test.js
  frontend/src/tests/pages/AdminStudentsIndexPage.test.js
Labels: 5, Merge Candidate-CI

#50 Add pageSize parameter to OurTable
  frontend/src/main/components/OurTable.js
  frontend/src/stories/components/OurTable.stories.js
Labels: 10, Merge Candidate-CI

#51 Improve Performance of Tests for OurTable
  frontend/src/tests/components/OurTable.test.js
Labels: 20, Merge Candidate-CI

#54 Create Placeholder Pages for Courses table
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminCoursesCreatePage.js
  frontend/src/main/pages/AdminCoursesEditPage.js
  frontend/src/main/pages/AdminCoursesIndexPage.js
  frontend/src/tests/pages/AdminCoursesCreatePage.test.js
  frontend/src/tests/pages/AdminCoursesEditPage.test.js
  frontend/src/tests/pages/AdminCoursesIndexPage.test.js
Labels: 5, Merge Candidate-CI

#60 Test all form fields in Create Commons end-to-end test
  src/test/java/edu/ucsb/cs156/happiercows/web/CommonsWebIT.java
Labels: 10, Ready-For-Staff, Merge Candidate-CI

#47 Create course controller with get all endpoint and tests
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CourseController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CourseControllerTests.java
Labels: 10, Merge Candidate-CI

#58 Add additional web integration test for other Commons functions
  src/test/java/edu/ucsb/cs156/happiercows/web/CommonsWebIT.java
Labels: 10, Merge Candidate-CI

#63 added web integration tests for buying and selling cows
  src/test/java/edu/ucsb/cs156/happiercows/web/UserCommonsWebIT.java
Labels: 10, Ready-For-Staff, Merge Candidate-CI
